CREATE TABLE user_roles_tbl (
  ACC_ID  INT NOT NULL,
  ROLE_ID INT NOT NULL,

  FOREIGN KEY (ACC_ID) REFERENCES account_tbl (ACC_ID),
  FOREIGN KEY (ROLE_ID) REFERENCES roles_tbl (ID),
  UNIQUE (ACC_ID, ROLE_ID)
);